### ISSUE TITLE
relax requirements of convertFromString

### ISSUE THREAD

**Issue by v-lopez** [BehaviorTree/BehaviorTree.CPP#34]
Don't fail compilation, send a warning instead

**Comment by facontidavide** [comment]
@mjeronimo for your information:

I decided to be less strict regarding convertFromString.

Now the program will compile even if the template specialization is missing.
If the NodeParameter points to a Blackboard, everything will work just fine since no string parsing is needed.

If either:

- NodeParameter was actually a string, not a pointer to a Blackboard entry __or__
- The Blackboard entry contains a string and you are trying to extract something else.

an exception is thrown, warning that you must implement your own __convertFromString__.

**Comment by mjeronimo** [comment]
@facontidavide Sounds reasonable. Thanks for the info.
