### ISSUE TITLE
What is the difference between getInput and blackboard->get()?

### ISSUE THREAD

**Issue by Zhuoqian0** [BehaviorTree/BehaviorTree.CPP#422]
Hi，
I have some question, what is the difference between getInput and blackboard->get(). Is there anything to pay attention to when using them?

Cheers!

**Comment by facontidavide** [comment]
The difference is that you must **never** use `blackboard->get()`.

I can guaranty that ports works as I describe in the Tutorials. If you use the blackboard directly there is an 80% probability that it does what you want, but I am not documenting it nor debug any problem you may have.

Said that: you may want to read the implementation of `getInput`:

This is simplified pseudo-code:

- if the port was not declared in `Node::providedPorts()`, fail.
- use `convertFromString` if you are passing a string instead of the name of an entry.
- access the blackboard in a thread safe way.
