### ISSUE TITLE
How to design a scalable tree

### ISSUE THREAD

**Issue by Zhuoqian0** [BehaviorTree/BehaviorTree.CPP#510]
Hi，

When a tree implements more and more functions, different nodes will depend on each other, causing some nodes to be used in combination with other nodes. Over time, the maintainability and scalability will deteriorate, and the learning cost of the tree will become higher. What strategy and development principles should I adopt to avoid this problem.

When I reconstructed the tree, I put the dismantling process of the task in the preprocessing, and only the most basic actions (eg walking, rotating) were kept in the tree. But this seems to lose the scalability of the tree. Do you have any suggestions and design ideas?

Thank you so much
Good luck

**Comment by facontidavide** [comment]
I have NO IDEA what your problem is without an example, I can only guess, so my answer may or may not be relevant.

The best way to make BT scalable is to follow the same rules you follow to make code in general scalable:

- **Functions ->Subtrees:** when coding, it is recommended to use small functions that do only one thing and have a clear name. Similarly, in BTs you are encouraged to use Subtree to create reusable and easy to read sub-behaviors.

- **Don't use hardcoded values -> use Ports as arguments**: you don't create actions GotToKitchen GoToBedroom, but instead a generic GoTo where destination is a port and is computed by another node.

- **Avoid Global variables -> use blackboard scoping**: blackboard scoping is a little bit annoying because of manual remap, but it is the only way to have `very_long_names_to_avoid_reusing_the_same_in_two_different_contexts`.

If you want to present a concrete example, I can be more specific
