### ISSUE TITLE
The code of bt create tree from file seems has running bug with subtrees in the same file?

### ISSUE THREAD

**Issue by a137755952** [BehaviorTree/BehaviorTree.CPP#542]
The version is 4.1, when I run the code below, the file contains descriptions of main tree and subtrees, I got the error of specified incorrectly.

auto tree = factory.createTreeFromFile(file); 
tree.tickWhileRunning();

While when I change the code to:

factory.registerBehaviorTreeFromFile(file);
auto tree = factory.createTree("MainTree");

the code is executed successfully.

**Comment by facontidavide** [comment]
You are not providing sufficient information to help you.

Can you share the specific error message and the XML?

Also, it is probably due to the fact that your file has multiple **BehaviorTrees** inside it and you need to specify with one is the "main".

Closing this issue until you provide more information.
