### ISSUE TITLE
How to precisely represent mathematical constants in XML file

### ISSUE THREAD

**Issue by alsora** [BehaviorTree/BehaviorTree.CPP#633]
Hi,

I have a behavior tree where some of the action nodes take floating point numbers as input.
Often these numbers are "hand-written" in the XML file as they are some constant value, rather than being computed by another action node.

Consider the following code
```xml
<Action ID="Rotate" input_angle="3.14"/>
```

Here I would like to rotate the robot of `pi` radians, however the above representation will potentially introduce an error due to how I'm defining the angle.
To get the expected result, I should rather do something like this:

```xml
<Action ID="Rotate" input_angle="3.1415926535897932384626433"/>
```

This can be error prone and make the code harder to read (imagine these huge decimal numbers in the context of a much larger behavior tree).

Would it be possible to add support for mathematical constants? That would allow to do something like
```xml
<Action ID="Rotate" input_angle="M_PI"/>
```

Another alternative would be to create a custom action node that converts a set of strings into floating point values, although I think that something like this could be directly integrated into the framework.
```xml
<Action ID="GetMathematicalConstat" input_name="M_PI" output_value="{pi}"/>
<Action ID="Rotate" input_angle="{pi}"/>
```

Do you have any thoughts?

**Comment by facontidavide** [comment]
Unfortunately, I have no solution to this. Also, I think it currently exceeds what I want to implement.

A potential solution could be to extend `convertFromString<double>()` to support the constant **M_PI**.

This would allow you to do
```xml
<Rotate input_angle="M_PI"/>
```

Otherwise, you can use the script (similar to your suggestion, but already built in)

```xml
<Script code="M_PI="3.1415926535897932384626433"/>
<Rotate input_angle="{M_PI}"/>
```

But the problem is that this variable is scoped and you should write it in each Subtree :cry: 

For the time being, I am not planning to add support to this.
