### ISSUE TITLE
Clarification needed: what is supposed to happen when forgetting curly braces for an output port in XML?

### ISSUE THREAD

**Issue by galou** [BehaviorTree/BehaviorTree.CPP#715]
What is supposed to happen with this XML excerpt?
```xml
<Sum a="{a}" b="{b}" sum="total" />
```
as opposed to the correctly written
```xml
<Sum a="{a}" b="{b}" sum="{total}" />
```

Now the code works but shouldn't we throw an exception?

**Comment by facontidavide** [comment]
## Input port

```xml
<SaySomething txt="hello" />
```
**txt** port receive a static string "hello"

```xml
<SaySomething txt="{greetings}" />
```
**txt** port points to the blackboard entry inside `greetings`

## Output port
```xml
<Sum a="{a}" b="{b}" sum="total" />
```
Illegal since version 4.4.2, because you can not write inside a static string, only inside a blackboard port, such as
Currently, this fails at run-time, but I am realizing that it should fail at deployment time!!!

**Comment by galou** [comment]
Ok, so I guess I should update. Thanks!
