### ISSUE TITLE
How to implement multi-threaded parallel execution of several sets of actions？

### ISSUE THREAD

**Issue by HBing110** [BehaviorTree/BehaviorTree.CPP#848]
I have a simple requirement, which is to run the following sets of actions in three threads. Could you please help me with how to implement them
![d985d69649756995ead408c3080aba36](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/49014760/811c21b2-7425-4fbc-bc7f-17f2b69cbd46)

**Comment by facontidavide** [comment]
In general, it is hard to create multi-thread in BehaviorTree, because you must find a way to make a thread interruptable when the halt signed is invoked.

See the second part of this video for details: https://youtu.be/7MZDBihsR_U?feature=shared&t=2939

You may experiment with a Decorator that spawn a new thread, or your own implementation of the Parallel Node.

But implementing this is not on my roadmap.
